Persist Left Panel Resize
cisagov/RedEye pull request #108
Opened 2023-03-27 02:09 UTC by arniebradfo

## Description ##
Give the text content in the left panel more room for readability.
- Left Panel is now a bit larger by default - 600px
- Left Panel now persists its resize between page reloads using window.localStorage
- The drag resize now more precise
- css grid layout is simplified
- Double clicking the dragger will reset the left panel to the default size
- I made a commit that persists the collapsed state of either panel, but the graph does not initialize properly if the panel its in starts collapsed. I reverted that change and left a note.

## Testing ##
- drag resize the left panel
- reload the page

## Screenshots ##

![Screen Shot 2023-03-26 at 6 55 22 PM](https://user-images.githubusercontent.com/6248614/227823859-c4e0a4e2-3a90-49c4-b7bb-5b6a5cb2378e.png)

2023-03-27 17:47 UTC, GoldingAustin approved these changes

2023-03-27 21:19 UTC, sang2925 commented
@arniebradfo I found a bug where if we refresh the page after resizing the left panel, the command log output disappears.

2023-03-27 21:20 UTC, sang2925 requested changes
https://user-images.githubusercontent.com/22081109/228069339-997dc4a0-662c-4224-9c75-b7d0cbd01379.mov

edit: it happens in develop too, so I will create a bug for it and change pr to approved.

2023-03-28 15:19 UTC, sang2925 approved these changes

2023-03-29 19:23 UTC, merged